name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v4

      - name: Create .env file locally
        run: |
          echo "BREADKUN_DB_URL=${{ secrets.BREADKUN_DB_URL }}" > .env
          echo "BREADKUN_DB_USERNAME=${{ secrets.BREADKUN_DB_USERNAME }}" >> .env
          echo "BREADKUN_DB_PASSWORD=${{ secrets.BREADKUN_DB_PASSWORD }}" >> .env
          echo "CIABATTA_CORE_PORT=${{ secrets.CIABATTA_CORE_PORT }}" >> .env
          echo "NGINX_SERVER_NAME=${{ secrets.NGINX_SERVER_NAME }}" >> .env
          echo "CORS_ORIGIN_1=${{ secrets.CORS_ORIGIN_1 }}" >> .env
          echo "CORS_ORIGIN_2=${{ secrets.CORS_ORIGIN_2 }}" >> .env
          echo "CORS_ORIGIN_3=${{ secrets.CORS_ORIGIN_3 }}" >> .env
          echo "CORS_ORIGIN_4=${{ secrets.CORS_ORIGIN_4 }}" >> .env
          echo "CORS_ORIGIN_5=${{ secrets.CORS_ORIGIN_5 }}" >> .env
          echo "SSR_SECRET_KEY=${{ secrets.SSR_SECRET_KEY }}" >> .env

      - name: Deploy .env using ssh-deploy
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.MASTER_SSH_HOST }}
          REMOTE_USER: ${{ secrets.MASTER_SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.MASTER_SSH_PORT }}
          SOURCE: .env
          TARGET: /home/${{ secrets.MASTER_SSH_USERNAME }}/deploy/.env
          SCRIPT_BEFORE: |
            rm -f /home/${{ secrets.MASTER_SSH_USERNAME }}/deploy/.env

      - name: Deploy docker-compose.yaml and restart containers
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.MASTER_SSH_HOST }}
          REMOTE_USER: ${{ secrets.MASTER_SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.MASTER_SSH_PORT }}
          SOURCE: docker-compose.yaml
          TARGET: /home/${{ secrets.MASTER_SSH_USERNAME }}/deploy/docker-compose.yaml
          SCRIPT_BEFORE: |
            rm -f /home/${{ secrets.MASTER_SSH_USERNAME }}/deploy/docker-compose.yaml
          SCRIPT_AFTER: |
            cd /home/${{ secrets.MASTER_SSH_USERNAME }}/deploy
            docker compose down || true
            docker compose up -d